[package]
name = "fire"
version = "0.1.0"
edition = "2021"

[dependencies.rocket_db_pools]
version = "0.2.0"
features = ["sqlx_sqlite"]

[dependencies.serde]
version = "1.0.208"

[dependencies.rocket]
version = "0.5.1"
features = ["secrets"]

[dependencies.sqlx]
version = "0.7.0"
default-features = false
features = ["macros", "migrate"]

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["tera"]
