[package]
name = "fire"
version = "0.1.0"
edition = "2021"

[dependencies.rocket_sync_db_pools]
version = "0.1.0"
features = ["diesel_sqlite_pool", "sqlite_pool"]

[dependencies.diesel]
version = "2"
features = ["sqlite", "returning_clauses_for_sqlite_3_35"]

[dependencies.serde]
version = "1.0.208"

[dependencies.rocket]
version = "0.5.1"
features = ["secrets"]

[dependencies.rocket_dyn_templates]
version = "0.2.0"
features = ["tera"]
