# fly.toml app configuration file generated for fire-floral-cloud-8780 on 2024-08-25T22:33:08Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'fire-floral-cloud-8780'
primary_region = 'sea'

[build]

[env]
  PORT = '8080'
  ROCKET_ADDRESS = '0.0.0.0'
  ROCKET_PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
